#!/bin/bash
rm comprimido.txt
rm comprimido2.txt
rm comprimido3.txt
rm comprimido4.txt
rm salida2.txt
rm salida3.txt
rm salida4.txt
rm salida.txt
rm texto_desc.txt
rm cancion_desc.mp3
rm imagen_desc.bmp
rm imagen2_desc.jpg
rm practica3
rm comprimido5.txt
rm salida5.txt
rm pdf_desc.pdf
rm salida6.txt
rm comprimido6.txt
rm word_desc.docx
rm comprimido7.txt
rm salida7.txt
rm imagen3_desc.png