#!/bin/bash
rm caracteres1.txt
rm caracteres2.txt
rm caracteres3.txt
rm caracteres4.txt
rm caracteres5.txt
rm caracteres6.txt
rm caracteres7.txt
rm texto_desc.txt
rm cancion_desc.mp3
rm imagen1_desc.bmp
rm imagen2_desc.jpg
rm imagen3_desc.png
rm pdf_desc.pdf
rm word_desc.docx
rm texto_comp.txt
rm cancion_comp.txt
rm imagen1_comp.txt
rm imagen2_comp.txt
rm imagen3_comp.txt
rm pdf_comp.txt
rm word_comp.txt
rm practica3